### ISSUE TITLE
Escaping fullscreen doesn't return image position/size

### ISSUE THREAD

**Issue by alecdotdev** [SWE-2023/COSC-4P02-Project#23]
Happens on some devices, not happening consistently.

Black background disappears after clicking to escape fullscreen, but image sticks to the screen taking up full width. Possibly just an issue with the npm package.

**Comment by ibhashmi** [comment]
Issue occurs consistently when leaving fullscreen using ESC button. Image breaks and only way to fix it is to switch to another year on the timeline or refresh the page

**Comment by alecdotdev** [comment]
Possible fix on timeline branch, no longer hangs with back (mobile) or ESC (desktop). Goes fullscreen but image still has `.image` CSS styling when in fullscreen mode.

**Comment by alecdotdev** [comment]
## Screen capture of current state when fullscreened:

![image](https://user-images.githubusercontent.com/18179415/232247384-7315aad1-9772-4d1d-9836-57ff08491ff6.png)

**Comment by haarisyahya** [comment]
Currently trying to find a fix to bypass the image CSS styles when in fullscreen, however, found a bug in mobile, when trying to zoom in using my fingers, it moves to another timeline item when zoomed in enough. Reverses itself when zooming out.

**Comment by alecdotdev** [comment]
> Currently trying to find a fix to bypass the image CSS styles when in fullscreen, however, found a bug in mobile, when trying to zoom in using my fingers, it moves to another timeline item when zoomed in enough. Reverses itself when zooming out.

I see. that's likely an issue caused by the swipe-to-navigate code. I'll take a look and see if theres a way to bypass swipe listening when using two finger pinch.

**Comment by alecdotdev** [comment]
Combining this with #22 

> Finger zooming on mobile doesn't work on full screen, check full screen pkg docs for workaround.
