### ISSUE TITLE
Add Cursor component to timeline sidebar

### ISSUE THREAD

**Issue by alecdotdev** [SWE-2023/COSC-4P02-Project#24]
Date indicator for the current item. Should transition (using spring) to other points on changing timeline items.

**Comment by alecames** [comment]
Just need to add navigation through arrow buttons/keys

**Comment by alecdotdev** [comment]
TODO: 
- [x] add mobile scrolling for timeline bar

BUGS:
- [x] re-adjust `timeline-container` to show Dot components that spill of the top and bottom getting cut off by hidden overflow.
- [x] fix positioning on mobile, size of buttons
- [x] fix scrolling overshoot behaviour nears extremities of timeline, e.g.: scrolling to the final year when zoomed won't show the last timeline item
